### ISSUE TITLE
关于摄像头的问题

### ISSUE THREAD

**Issue by TKONIY** [TKONIY/Canteen-Info-System#18]
我上网查了一下，现在海康威视的摄像头基本上都是带了ip地址的，如果能联网的甚至有公网ip。我已经找到了通过它的ip地址和用户名密码拉取视频流的方法，很简单。当然我们可以自己买一个海康威视装在上面然后联网，但是我觉得如果饭堂能直接给我们提供账号密码会更好。所以我可能还是需要先去找一下饭堂的负责人。大家讨论一下对这个事情的看法。

**Comment by TKONIY** [comment]
现在的几种方案：

- 要到所有摄像头的公网ip和密码，在服务器上可以随时随地读取视频流，并可以完备地统计单层楼的全部人数。

- 只有内网ip，服务器翻墙进bupt校园网读视频流（实现难度未知）。

- 啥都要不到，我们自己买一个能联网的海康威视摄像头（￥200-300），服务器联网拉取视频流。要花钱而且只能看到部分人流量。

询问过导员，我们需要去后勤处/保卫处咨询。

**Comment by buptdjy** [comment]
先和食堂沟通下吧，不过我觉得希望不大

**Comment by buptdjy** [comment]
然后摄像头问题不知道能不能用一个手机或者pad达到功能

**Comment by TKONIY** [comment]
食堂我明天去沟通，说说我不考虑用手机的原因：手机和ipad到了实际业务场景就是和摄像头完全不一样的东西，并且我们根本没有时间去一边举着手机一边调试，还有，手机有手机的系统，和服务器进行视频流传输比海康威视一条命令RTSP推流要麻烦得多。

**Comment by arnoldzhu** [comment]
OK，我其实当时跟你说用手机就是想看看真正用自己的数据训练一个网络模型大概是怎么样的一个流程。

**Comment by arnoldzhu** [comment]
明天我和你一起去食堂沟通，到时候有任何进展都放到这上面。

**Comment by will-178** [comment]
我觉得可以先和饭堂沟通，不过感觉还挺困难的，可以试着按老师之前说的来做。

**Comment by will-178** [comment]
我觉得可以先和饭堂沟通，不过感觉还挺困难的，可以试着按老师之前说的来做。

**Comment by TKONIY** [comment]
Emm..记录一下现在的计划吧。
1. 购买支持RTMP协议的摄像头(直播平台使用)。
2. 学习如何使用RTMP推流

- [ ] 低纬度

**Comment by TKONIY** [comment]
互联网传输协议：只有rtmp
大部分憨憨摄像头的协议：无
部分专业摄像头：rtsp局域网协议
我把我的工作分为几个部分：

- [ ] 学会使用opencv读取rtmp

- [ ] 寻找rtmp摄像头，如果没有就只能扛电脑去自己将rtsp转rtmp推流

**Comment by TKONIY** [comment]
方案1 : rtmp
1. 购买支持rtmp协议的摄像头。
2. 搭建rtmp服务器。（重新编译 or docker）
3. 串流，将摄像头的流直接推到服务器上。


方案2：socket
1. 购买普通摄像头：支持rtsp协议。
2. 用自己电脑在局域网(校园网)拉摄像头的rtsp流。
3. 在电脑上使用OBS(GUI)或ffmpeg(库)转换为socket推流。

现在我的opencv能读rtmp了，但是现在的问题是买不到支持rtmp协议的摄像头，特别烦，我寒假回华强北找一波。而且rtmp一般是用来做直播的，服务器搭建很困难，我觉得我很难在服务器上搭建好rtmp环境，网上教程有不少，也有提供[docker](https://www.jianshu.com/p/4b6f442c8526)。但是由于我现在确实搞不到rtmp摄像头，也不想用买了rtsp摄像头转rtmp推流。所以我接下来的计划是先尝试使用socket通信。
