### ISSUE TITLE
朱孟德任务11.28-12.11

### ISSUE THREAD

**Issue by arnoldzhu** [TKONIY/Canteen-Info-System#20]
1.阅读微信官方文档，学习云开发的具体过程。 #16 
2.上网查相关资料，弄懂前后端如何建立联系。
3.和tkoniy一起和食堂沟通，确定是否要买摄像头/怎么用摄像头。 #18

**Comment by TKONIY** [comment]
写成可以打钩的形式吧，方便看进度。
