### ISSUE TITLE
微信小程序学习视频

### ISSUE THREAD

**Issue by buptdjy** [TKONIY/Canteen-Info-System#22]
视频比较老，但是讲的挺好的，大家选择观看就行了，不用每个都看，个人建议看到p15左右然后后面的选择观看，[https://www.bilibili.com/video/av11938917/](url)

**Comment by buptdjy** [comment]
看完部分视频如果还是不太理解可以在图书馆借到相关书籍或者在网上找到电子版

**Comment by will-178** [comment]
收到

**Comment by TKONIY** [comment]
OK，谢了

**Comment by TKONIY** [comment]
这里有比较新的课程，官网的。
https://cloud.tencent.com/edu/paths/series/applet

**Comment by will-178** [comment]
@TKONIY 好的好的

**Comment by will-178** [comment]
https://www.bilibili.com/video/av25037513?from=search&seid=6914945230095093160 这个是b站上那个邓学长官网的视频，我觉得B站好操作些所以分享下
