### ISSUE TITLE
讨论：会议纪要与文档如何保存？

### ISSUE THREAD

**Issue by TKONIY** [TKONIY/Canteen-Info-System#4]
1. 我们的PPT，申请书等文件是否需要放到github上面？
2. 会议纪要是通过word保存还是直接记录为issue？

**Comment by TKONIY** [comment]
我的想法是，ppt等不涉及个人资料的文件可以上传，并且有分享价值。每一次会议可以当作一个issue，会议发起者提前提出issue，大家在这里讨论下会议时间和内容。开会结束后我在issue的描述那里添加会议纪要。

**Comment by buptdjy** [comment]
放wx群上吧。。

**Comment by arnoldzhu** [comment]
1.我觉得PPT申请书这些文件（和所有有关我们这个项目的文件）都要放到GitHub上面，保持项目的完整性，做好分类归档的工作就好。当然也要传到微信上面，方便用手机随时查看。
2.会议纪要放在issue上即可，一个会议纪要对应一个issue会比较清晰。

**Comment by will-178** [comment]
放Github上，但是要保证个人信息没有就行

**Comment by TKONIY** [comment]
好的，谢谢大家的意见😁，从周三的会议开始我尝试整理一下，传资料到github上。项目申请书我可以抽出项目内容部分做成md格式上传。全部在docs分支操作，不设置权限大家随时可以上传。还没merge到master/dev之前大家直接去那个分支看文档就行。
