### ISSUE TITLE
学习github

### ISSUE THREAD

**Issue by TKONIY** [TKONIY/Canteen-Info-System#6]
使用github desktop/git完成以下任务：
为自己负责的模块新建一个分支，进行修改，并发出一个从该分支到dev分支的merge请求（pull request)。

- [x] @buptdjy 

- [x] @will-178 

- [x] @lochson 

- [x] @arnoldzhu

**Comment by arnoldzhu** [comment]
已发送pull request,等待审核

**Comment by TKONIY** [comment]
@arnoldzhu 
Congratulations !👏

但是还是有一些地方需要注意：

- [x] 我们仓库下只有一个project，打开project面板，可以看我之前的issue了解自动化机制也可以选择manage选项查看。再说一次：当一个任务开始时，assignees需要将issue移动到In progress看板，让团队知道大致进度。

- [x]  右边工具栏的`Milestone` `Projects` `labels` `Assignees`这几项是必须选择的，后期issue会很多，需要精确又简洁地通过这几个选项描述才可以让我们的项目有条理。

- [x] 关于pull requests，标题最好不要写默认的，最好能简洁描述修改内容，如果大家都用默认的update xxx就会降低工作效率。

- [x] 关于pull request，再提一次：1. 看一次ppt，以及ppt中提到的官方文档，2. 我给dev和master分支开的权限分别是需要初提交者以外的3个和4个reviewer的approve，如果不想让自己的pull request等到地老天荒，那提出pull request的时候请别忘了添加足够的reviewer。

看懂了就✔，不懂就下面提问叭😀

顺便艾特一下这三位还没开始任务的小伙伴过来瞧一瞧
@buptdjy @will-178 @lochson
